SELECT * FROM myemp ORDER BY MGR_ID ASC;
SELECT * FROM myemp ORDER BY MGR_ID DESC;
SELECT * FROM myemp ORDER BY SALARY DESC, FIRST_NAME ASC;
SELECT * FROM myemp LIMIT 15;
SELECT * FROM myemp LIMIT 5 OFFSET 5;
SELECT * FROM myemp LIMIT 15,10;
SELECT DISTINCT(HIRE_DATE) FROM myemp;
SELECT * FROM myemp ORDER BY HIRE_DATE ASC LIMIT 5;
SELECT * FROM myemp ORDER BY SALARY DESC LIMIT 2,1;
SELECT DISTINCT(SALARY) FROM myemp ORDER BY SALARY DESC LIMIT 3;
SELECT SUM(SALARY) FROM myemp;
SELECT COUNT(SALARY) FROM myemp;
SELECT MIN(SALARY) FROM myemp;
SELECT MAX(SALARY) FROM myemp;
SELECT AVG(SALARY) FROM myemp;
SELECT SUM(SALARY),COUNT(SALARY),MIN(SALARY),MAX(SALARY),AVG(SALARY) FROM myemp;
SELECT COUNT(DISTINCT(DEP_ID)) FROM myemp;
SELECT DEP_ID,SUM(SALARY) FROM MYEMP GROUP BY DEP_ID;
SELECT DEP_ID,JOB_ID,COUNT(EMP_ID) FROM MYEMP GROUP BY DEP_ID,JOB_ID;
SELECT DEP_ID,SUM(SALARY) AS TOTAL_SALARY FROM MYEMP GROUP BY DEP_ID HAVING SUM(SALARY)>10000;
SELECT DEP_ID,JOB_ID,COUNT(EMP_ID) FROM MYEMP GROUP BY DEP_ID,JOB_ID HAVING COUNT(EMP_ID)>2;
SELECT DEP_ID, AVG(SALARY) AS AVG_SALARY FROM MYEMP WHERE JOB_ID!="SA_REP" GROUP BY DEP_ID HAVING AVG_SALARY>7000;
SELECT *, CASE
WHEN SALARY<7000 THEN "LOW"
WHEN SALARY BETWEEN 7000 AND 15000 THEN "MEDIUM"
ELSE "HIGH"
END AS SAL_STATUS
FROM MYEMP;
SELECT *, CASE
WHEN SALARY<7000 THEN SALARY+1000
WHEN SALARY BETWEEN 7000 AND 15000 THEN SALARY+2000
ELSE SALARY+3000
END AS BONUS
FROM MYEMP;



