CREATE DATABASE CONSTRAINTS;
CREATE TABLE EMP(ID INT, NAME VARCHAR(50) DEFAULT "NA", AGE INT);
CREATE TABLE STUDENTS(ID INT , NAME VARCHAR(50) DEFAULT "NA", AGE INT DEFAULT 0);
ALTER TABLE STUDENTS MODIFY COLUMN ID INT NOT NULL;
DESC STUDENTS;
ALTER TABLE STUDENTS ADD COLUMN EMAIL_ID VARCHAR(50) UNIQUE;
CREATE TABLE PARTICIPENTS(ID INT , NAME VARCHAR(50) DEFAULT "NA", COURSE_ID INT, CONSTRAINT UNIQUE(ID,COURSE_ID));
DESC PARTICIPENTS;
ALTER TABLE PARTICIPENTS ADD COLUMN AGE INT CHECK(AGE>=18);
ALTER TABLE PARTICIPENTS ADD COLUMN DESIGNATION VARCHAR(50);
CREATE TABLE PRODUCTS(PRO_ID INT , PRO_NAME VARCHAR(50), PRO_PRICE INT, CONSTRAINT OG PRIMARY KEY(PRO_ID,PRO_PRICE));
DESC PRODUCTS;
USE CONSTRAINTS;
CREATE TABLE PERSONS(PID INT PRIMARY KEY,NAME VARCHAR(50),AGE INT);
CREATE TABLE ORDERS(OID INT PRIMARY KEY,ONUM INT,PID INT,CONSTRAINT FK FOREIGN KEY(PID) REFERENCES PERSONS(PID));
DESC ORDERS;
CREATE TABLE SHIPMENTS(SID INT PRIMARY KEY, DATE_TIME TIME, R_TIME TIME);
CREATE TABLE CUSTOMERS(CID INT PRIMARY KEY, NAME VARCHAR(50), AGE INT);
CREATE TABLE PRODUCT(PID INT PRIMARY KEY, NAME VARCHAR(50), SALES FLOAT);
CREATE TABLE SALES(ID INT PRIMARY KEY, SID INT, CID INT, PID INT, SALES FLOAT,CONSTRAINT FK1 FOREIGN KEY(SID) REFERENCES SHIPMENTS(SID),CONSTRAINT FK2 FOREIGN KEY(CID) REFERENCES CUSTOMERS(CID),CONSTRAINT FK3 FOREIGN KEY(PID) REFERENCES PRODUCT(PID));
DESC SALES;
CREATE TABLE BOOKS(BID INT PRIMARY KEY AUTO_INCREMENT, CATEGORY VARCHAR(50));
ALTER TABLE BOOKS AUTO_INCREMENT=100;
DESC BOOKS;



