SELECT * FROM SALES;
WITH YEAR_SALES AS
(SELECT FISCAL_YEAR,SUM(SALE) TOTAL_SALES FROM SALES GROUP BY FISCAL_YEAR)
SELECT * FROM YEAR_SALES WHERE TOTAL_SALES>500;
WITH YEAR_SALES AS
(SELECT FISCAL_YEAR,SUM(SALE) TOTAL_SALES FROM SALES GROUP BY FISCAL_YEAR)
SELECT * FROM YEAR_SALES;
WITH TEMP AS
(SELECT DRINKNAME,D.RATE DRATE,MEALNAME,M.RATE MRATE, (D.RATE+M.RATE) COMB0_PRICES, (D.RATE+M.RATE)*0.05+(D.RATE+M.RATE) COMB0_PRICES_GST  FROM DRINKS D CROSS JOIN MEALS M)
SELECT * FROM TEMP WHERE COMB0_PRICES_GST>35;
