-- Creating a DataBase
CREATE DATABASE TARUN;
use TARUN;
create table Emp(ID INT,Name VARCHAR(50),Salary INT);
DROP DATABASE Tarun;
create database XYZ_PVT_LMT;
use XYZ_PVT_LMT;
create table PRODUCTS(PRO_ID INT, PRO_NAME VARCHAR(50),CATEGORY VARCHAR(50),SUB_CATEGORY VARCHAR(50));
create table EMPLOYEES(EMP_ID INT, NAME VARCHAR(50),AGE INT,GENDER ENUM("MALE","FEMALE"),HIRING_DATE TIMESTAMP,PHOTO BLOB);
ALTER TABLE EMPLOYEES
MODIFY HIRING_DATE DATE;
ALTER TABLE EMPLOYEES
ADD COLUMN D_O_B DATE;
-- FIRST POSITION
ALTER TABLE EMPLOYEES
ADD COLUMN QUALIFICATION VARCHAR(50) FIRST;
-- SPECIFIC POSITION
ALTER TABLE EMPLOYEES
ADD COLUMN DESIGNATION VARCHAR(50) AFTER GENDER;
ALTER TABLE EMPLOYEES DROP COLUMN DESIGNATION;
ALTER TABLE EMPLOYEES
ADD COLUMN SALARY INT,ADD COLUMN HIKE INT;
ALTER TABLE EMPLOYEES DROP COLUMN SALARY , DROP COLUMN HIKE;
ALTER TABLE EMPLOYEES MODIFY COLUMN D_O_B BLOB FIRST;
ALTER TABLE EMPLOYEES RENAME COLUMN QUALIFICATION TO EMP_QUALIFICATION;
RENAME TABLE EMPLOYEES TO EMPLOYEE;
/*OR ALTER TABLE EMPLOYEES RENAME TO EMPLOYEE*/
DROP TABLE PRODUCTS;
TRUNCATE TABLE EMPLOYEE;