SELECT * FROM AUTHORS;
SELECT OFFICECODE,PHONE FROM offices;
SELECT DISTINCT(JOB_ID) FROM myemp;
SELECT DISTINCT(JOB_ID),SALARY FROM myemp;
SELECT *, SALARY+10000 FROM myemp;
SELECT *, SALARY+10000 AS BONUS FROM myemp;
SELECT *, SALARY+10000 BONUS FROM myemp;
SELECT * FROM employees WHERE officeCode=1;