 -- BASIC FUNCTIONS
 -- SCALAR
 
 -- STRING
 -- 1)LEFT()
 SELECT JOB_ID,LEFT(JOB_ID,2) AS DEPT FROM MYEMP;
 -- 2)RIGHT()
  SELECT JOB_ID,RIGHT(JOB_ID,4) AS ROLE FROM MYEMP;
-- 3)UPPER()
SELECT EMAIL,UPPER(EMAIL) AS UPPER FROM MYEMP;
 -- 4)LOWER()
SELECT EMAIL,LOWER(EMAIL) AS LOWER FROM MYEMP;
 -- 5)LEN()
SELECT JOB_ID,LENGTH(JOB_ID) AS LENGTH FROM MYEMP;

-- NUMERIC
SELECT ABS(-7);
-- CEIL
SELECT MRP,CEIL(MRP) FROM PRODUCTS;
-- ROUND
SELECT MRP,ROUND(MRP) FROM PRODUCTS;
SELECT MRP,ROUND(MRP,2) FROM PRODUCTS;
-- FLOOR
SELECT MRP,FLOOR(MRP) FROM PRODUCTS;

-- DATE AND TIME
SELECT HIRE_DATE,YEAR(HIRE_DATE) AS YEAR FROM MYEMP;
SELECT HIRE_DATE,MONTH(HIRE_DATE) AS MONTH FROM MYEMP;
SELECT HIRE_DATE,DAY(HIRE_DATE) AS DAY FROM MYEMP;
SELECT HIRE_DATE,QUARTER(HIRE_DATE) AS QUARTER FROM MYEMP;
SELECT HIRE_DATE,WEEK(HIRE_DATE) AS WEEK FROM MYEMP;
SELECT NOW();
SELECT TIME(NOW());
SELECT DATE(NOW());
SELECT TIME,HOUR(TIME),MINUTE(TIME),SECOND(TIME) FROM TRAINS;
SELECT HIRE_DATE,DATEDIFF(DATE(NOW()),HIRE_DATE) FROM MYEMP;
SELECT HIRE_DATE,TIMESTAMPDIFF(YEAR,HIRE_DATE,DATE(NOW())) FROM MYEMP;
SELECT HIRE_DATE,TIMESTAMPDIFF(MONTH,HIRE_DATE,DATE(NOW())) FROM MYEMP;

-- WINDOW FUNCTIONS
 -- AGGREGATE FUNCTIONS
SELECT FIRST_NAME,AVG(SALARY) OVER() FROM MYEMP;
SELECT FIRST_NAME,DEP_ID,AVG(SALARY) OVER() FROM MYEMP;
SELECT FIRST_NAME,DEP_ID,AVG(SALARY) OVER(PARTITION BY DEP_ID) FROM MYEMP;
SELECT *,COUNT(EMP_ID) OVER(PARTITION BY DEP_ID) AS EMP_FROM_EACH_DEP FROM MYEMP; 
 
-- RANKING
  -- RANK
SELECT * , RANK() OVER() FROM MYEMP;
SELECT * , RANK() OVER(ORDER BY SALARY DESC) FROM MYEMP;
SELECT * , RANK() OVER(PARTITION BY DEP_ID ORDER BY SALARY DESC) FROM MYEMP;
 -- DENSE RANK
SELECT * , DENSE_RANK() OVER(ORDER BY SALARY DESC) FROM MYEMP;
SELECT * , DENSE_RANK() OVER(PARTITION BY DEP_ID ORDER BY SALARY DESC) FROM MYEMP;
 -- ROW NUMBER
SELECT * , ROW_NUMBER() OVER(ORDER BY SALARY DESC) FROM MYEMP;
SELECT * , ROW_NUMBER() OVER(PARTITION BY DEP_ID ORDER BY SALARY DESC) FROM MYEMP;
 -- NTILE
SELECT *, NTILE(5) OVER() FROM MYEMP;
SELECT *, NTILE(3) OVER(ORDER BY SALARY DESC) FROM MYEMP;
SELECT *, NTILE(3) OVER(PARTITION BY DEP_ID ORDER BY SALARY DESC) FROM MYEMP;

-- ANALYTICAL/OFFSET/VALUE FUNCTIONS
 -- FIRST VALUE 
SELECT *, FIRST_VALUE(FIRST_NAME) OVER() FROM MYEMP;
SELECT *, FIRST_VALUE(FIRST_NAME) OVER(PARTITION BY DEP_ID) AS FIRST_NAME_FROM_EACH_DEPT FROM MYEMP;
SELECT *, FIRST_VALUE(FIRST_NAME) OVER(PARTITION BY DEP_ID ORDER BY SALARY DESC) AS FIRST_NAME_FROM_EACH_DEPT FROM MYEMP;
 -- LAST VALUE 
SELECT *, LAST_VALUE(FIRST_NAME) OVER() FROM MYEMP;
SELECT *, LAST_VALUE(FIRST_NAME) OVER(PARTITION BY DEP_ID) AS FIRST_NAME_FROM_EACH_DEPT FROM MYEMP;
SELECT *, LAST_VALUE(FIRST_NAME) OVER(PARTITION BY DEP_ID ORDER BY SALARY DESC) AS FIRST_NAME_FROM_EACH_DEPT FROM MYEMP;
 -- NTH VALUE 
SELECT *, NTH_VALUE(SALARY,3) OVER() FROM MYEMP;
SELECT *, NTH_VALUE(SALARY,3) OVER(PARTITION BY DEP_ID) AS FIRST_NAME_FROM_EACH_DEPT FROM MYEMP;
SELECT *, NTH_VALUE(SALARY,3) OVER(PARTITION BY DEP_ID ORDER BY SALARY DESC) AS FIRST_NAME_FROM_EACH_DEPT FROM MYEMP;
 -- LEAD
SELECT * FROM SALES;
SELECT *,LEAD(SALE) OVER() FROM SALES;
SELECT *,LEAD(SALE) OVER(PARTITION BY SALES_EMPLOYEE) FROM SALES;

  -- LAG
SELECT *,LAG(SALE) OVER() FROM SALES;
SELECT *,LAG(SALE) OVER(PARTITION BY SALES_EMPLOYEE) FROM SALES;

WITH TEMP AS
(SELECT *, DENSE_RANK() OVER(ORDER BY SALARY) AS RANKS FROM MYEMP)
SELECT * FROM TEMP WHERE RANKS=10;

WITH TEMP2 AS
(WITH TEMP AS
(SELECT FISCAL_YEAR,SUM(SALE) AS CURR_YEAR_SALES FROM SALES GROUP BY FISCAL_YEAR)
SELECT *,LAG(CURR_YEAR_SALES) OVER() AS PREV_SALES FROM TEMP)
SELECT *,((CURR_YEAR_SALES-PREV_SALES)/PREV_SALES)*100 AS GROWTH_PERCTENTAGE FROM TEMP2;










