SELECT * FROM MYEMP;
SELECT * FROM MEALS;
SELECT * FROM DRINKS CROSS JOIN MEALS;
SELECT *, DRINKS.RATE+DRINKS.RATE AS COMB0_PRICE FROM DRINKS CROSS JOIN MEALS;
SELECT *, (DRINKS.RATE+MEALS.RATE) AS COMB0_PRICE, (DRINKS.RATE+MEALS.RATE)*0.05+(DRINKS.RATE+MEALS.RATE) AS COMB0_PRICE_GST  FROM DRINKS CROSS JOIN MEALS;
SELECT D.*, M.*, (D.RATE + M.RATE) AS COMBO_PRICE,((D.RATE + M.RATE) * 0.05 + (D.RATE + M.RATE)) AS COMBO_PRICE_GST FROM DRINKS D CROSS JOIN MEALS M;
SELECT * FROM MOVIES;
SELECT * FROM MEMBERS;
SELECT * FROM BOOKS INNER JOIN AUTHORS ON BOOKS.AUTHORID=AUTHORS.AUTHORID;
SELECT BOOKID,TITLE,AUTHORS.AUTHORID,NAME FROM BOOKS INNER JOIN AUTHORS ON BOOKS.AUTHORID=AUTHORS.AUTHORID;
SELECT * FROM MOVIES INNER JOIN MEMBERS ON MOVIES.ID=MEMBERS.MOVIEID;
SELECT * FROM AUTHORS LEFT JOIN BOOKS ON AUTHORS.AUTHORID=BOOKS.AUTHORID;
SELECT * FROM MEMBERS LEFT JOIN MOVIES ON MOVIEID=ID;
SELECT * FROM BOOKS RIGHT JOIN AUTHORS ON BOOKS.AUTHORID=AUTHORS.AUTHORID;
SELECT * FROM MOVIES RIGHT JOIN MEMBERS ON ID=MOVIEID;
SELECT FNAME,LNAME FROM PERSON UNION SELECT FNAME,LNAME FROM PERSON;
SELECT FNAME,LNAME FROM PERSON UNION ALL SELECT FNAME,LNAME FROM PERSON;
SELECT FNAME,LNAME FROM PERSON UNION SELECT FIRST_NAME,LAST_NAME FROM EMP;
SELECT FNAME,LNAME FROM PERSON UNION ALL SELECT FIRST_NAME,LAST_NAME FROM EMP;
-- FULL JOIN(UNION)
SELECT * FROM AUTHORS LEFT JOIN BOOKS ON AUTHORS.AUTHORID=BOOKS.AUTHORID
UNION
SELECT * FROM AUTHORS RIGHT JOIN BOOKS ON AUTHORS.AUTHORID=BOOKS.AUTHORID;
-- FULL JOIN(UNION ALL)
SELECT * FROM AUTHORS LEFT JOIN BOOKS ON AUTHORS.AUTHORID=BOOKS.AUTHORID
UNION ALL
SELECT * FROM AUTHORS RIGHT JOIN BOOKS ON AUTHORS.AUTHORID=BOOKS.AUTHORID;
SELECT * FROM BOOKS NATURAL JOIN AUTHORS;
SELECT * FROM MOVIES NATURAL JOIN MEMBERS;
SELECT * FROM MYEMP T1
JOIN MYEMP T2
ON T1.MGR_ID=T2.EMP_ID;
SELECT * FROM MYEMP T1
JOIN MYEMP T2
ON T1.EMP_ID=T2.MGR_ID;
SELECT T1.EMP_ID,T1.FIRST_NAME,T1.LAST_NAME,T1.MGR_ID,T2.FIRST_NAME AS MGR_FNAME,T2.LAST_NAME AS MGR_LNAME FROM MYEMP T1
JOIN MYEMP T2 
ON T1.EMP_ID=T2.MGR_ID;

SELECT T1.EMP_ID,T1.FIRST_NAME,T1.LAST_NAME,T1.MGR_ID,T1.SALARY,T2.FIRST_NAME AS MGR_FNAME,T2.LAST_NAME,T2.SALARY AS MGR_LNAME FROM MYEMP T1
JOIN MYEMP T2 
ON T1.EMP_ID=T2.MGR_ID
AND T1.SALARY>T2.SALARY;