SELECT * FROM myemp WHERE SALARY>10000 AND DEP_ID=90;
SELECT * FROM myemp WHERE DEP_ID=100 OR DEP_ID=90;
SELECT * FROM myemp WHERE NOT DEP_ID=90; -- EXCLUDE'S DEP_ID=90
SELECT DISTINCT(MGR_ID) FROM myemp;
SELECT * FROM myemp;
SELECT * FROM myemp WHERE (MGR_ID=100 OR MGR_ID=108 OR MGR_ID=120 OR MGR_ID=121) AND (NOT JOB_ID="ST_CLERK") AND (SALARY>12000);
SELECT * FROM myemp WHERE SALARY>7000;
SELECT * FROM myemp WHERE SALARY<=7000;
SELECT * FROM myemp WHERE HIRE_DATE>="1990-01-01";
SELECT * FROM myemp WHERE SALARY=10000;
SELECT * FROM myemp WHERE JOB_ID="IT_PROG";
SELECT * FROM myemp WHERE JOB_ID!="IT_PROG";
SELECT EMP_ID,concat(FIRST_NAME," ",LAST_NAME) AS FULL_NAME FROM myemp;
SELECT EMP_ID,concat(FIRST_NAME," ",LAST_NAME) AS FULL_NAME,CONCAT(EMAIL,"@GMAIL.COM") AS GMAIL FROM myemp;
SELECT * FROM myemp WHERE DEP_ID IN (90,100,120,121);
SELECT * FROM myemp WHERE JOB_ID NOT IN ("AD_PRES","FI_MGR");
SELECT * FROM myemp WHERE SALARY BETWEEN 5000 AND 10000;
SELECT * FROM myemp WHERE HIRE_DATE BETWEEN "1992-01-01" AND "2005-12-31";
SELECT * FROM offices WHERE STATE IS NULL;
SELECT * FROM offices WHERE STATE IS NOT NULL;
SELECT * FROM myemp WHERE JOB_ID LIKE "SA%";
SELECT * FROM myemp WHERE FIRST_NAME LIKE "A___";
SELECT * FROM myemp WHERE JOB_ID NOT LIKE "SA%";
SELECT * FROM myemp WHERE FIRST_NAME LIKE "%R%";









