SELECT * FROM myemp WHERE FIRST_NAME="NANCY";
SELECT * FROM myemp WHERE SALARY>12000;
SELECT * FROM myemp WHERE SALARY>(SELECT SALARY FROM myemp WHERE FIRST_NAME="NANCY");
SELECT * FROM myemp WHERE DEP_ID = (SELECT DEP_ID FROM myemp WHERE FIRST_NAME="NANCY");
SELECT * FROM myemp WHERE DEP_ID = (SELECT DEP_ID FROM myemp WHERE FIRST_NAME="JOHN");
SELECT DEP_ID FROM myemp WHERE FIRST_NAME="JOHN";
-- MULTI-VALUED OUTPUT
SELECT * FROM myemp WHERE DEP_ID IN (SELECT DEP_ID FROM myemp WHERE FIRST_NAME="JOHN");
SELECT * FROM myemp WHERE DEP_ID NOT IN (SELECT DEP_ID FROM myemp WHERE FIRST_NAME="JOHN");
SELECT SALARY FROM myemp WHERE FIRST_NAME IN ("AMIT","NANCY");
SELECT * FROM myemp WHERE SALARY > ANY (SELECT SALARY FROM myemp WHERE FIRST_NAME IN ("AMIT","NANCY"));
-- NESTED SUB-QUERY
SELECT MAX(SALARY) FROM myemp WHERE SALARY<(SELECT MAX(SALARY) FROM myemp WHERE SALARY<(SELECT MAX(SALARY) FROM myemp));
SELECT * FROM MYEMP WHERE SALARY =
(SELECT MAX(SALARY) FROM myemp WHERE SALARY<(SELECT MAX(SALARY) FROM myemp));
-- OR
SELECT * FROM MYEMP WHERE SALARY =
(select DISTINCT(SALARY) FROM MYEMP ORDER BY SALARY DESC LIMIT 1,1);
SELECT * FROM (SELECT *, RATE+(RATE*0.05) AS FINAL_RATE FROM DRINKS) AS DR;
SELECT * FROM
(SELECT DRINKNAME,D.RATE DRATE,MEALNAME,M.RATE MRATE, (D.RATE+M.RATE) COMB0_PRICES, (D.RATE+M.RATE)*0.05+(D.RATE+M.RATE) COMB0_PRICES_GST  FROM DRINKS D CROSS JOIN MEALS M) AS ML;
SELECT MEALNAME,AVG(COMB0_PRICES_GST) FROM
(SELECT DRINKNAME,D.RATE DRATE,MEALNAME,M.RATE MRATE, (D.RATE+M.RATE) COMB0_PRICES, (D.RATE+M.RATE)*0.05+(D.RATE+M.RATE) COMB0_PRICES_GST  FROM DRINKS D CROSS JOIN MEALS M) AS ML GROUP BY MEALNAME;

