SELECT * FROM T;
SET SQL_SAFE_UPDATES = 0;
DELETE FROM T WHERE VAL=2;
ROLLBACK;
SET AUTOCOMMIT=0;
DELETE FROM T WHERE VAL=4;
ROLLBACK;
COMMIT;
SELECT * FROM TRAINS;
START TRANSACTION;
INSERT INTO TRAINS VALUES(111,"SECUNDRABAD","10:30:00");
UPDATE TRAINS SET TIME="11:54:00" WHERE STATION="REDWOOD CITY";
DELETE FROM TRAINS WHERE TRAIN_ID=120;
ROLLBACK; -- TO UNDO CHANGES
-- COMMIT -> TO SAVE CHANGES
START TRANSACTION;
INSERT INTO TRAINS VALUES(111,"SECUNDRABAD","10:30:00");
SAVEPOINT S2;
UPDATE TRAINS SET TIME="11:54:00" WHERE STATION="REDWOOD CITY";
DELETE FROM TRAINS WHERE TRAIN_ID=120;
ROLLBACK TO S2;