SELECT * FROM myemp;
CREATE VIEW EMP_DEP_50 AS (SELECT * FROM myemp WHERE DEP_ID=50);
SELECT * FROM EMP_DEP_50;
CREATE VIEW DRM AS
(SELECT DRINKNAME,D.RATE DRATE,MEALNAME,M.RATE MRATE, (D.RATE+M.RATE) COMB0_PRICES, (D.RATE+M.RATE)*0.05+(D.RATE+M.RATE) COMB0_PRICES_GST  FROM DRINKS D CROSS JOIN MEALS M);
SELECT * FROM DRM;
ALTER VIEW EMP_DEP_50 AS (SELECT * FROM MYEMP WHERE DEP_ID=60);
DROP VIEW EMP_DEP_50;
INSERT INTO EMP_DEP_50 VALUES(2001,"STARK","TONY","IRONMAN","2010-08-12","IR_MAN",70000,0.00,300,50);
SET SQL_SAFE_UPDATES=0;
UPDATE EMP_DEP_50 SET SALARY=30000 WHERE EMP_ID=2001;
DELETE FROM EMP_DEP_50 WHERE EMP_ID=2001;